openapi: 3.0.3
info:
  title: API Test
  description: |-
    This is the description.
servers:
  -url: http://localhost:5000/
paths:
  /:
    get:
      parameters:
        - description: ...
          name: Get
          in: query
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/'
    post:
      description: ...
      parameters:
        - name: Post
          in: query
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/'



