openapi: '3.0.2'
info:
  title: simpel web server
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  
  /get:
    get:
      responses:
        '200':
          description: ok 
  /post:
    post:
      responses:
        default:
          description: succsesful
          

          